version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    networks:
      - backend
#    network_mode: "host"


  mongo:
    image: mongo:latest
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
#    volumes:
#      - redis_data:/data
    networks:
      - backend

volumes:
  mongo_data:
  redis_data:

networks:
  backend: